[versions]
"0.24.0" = { created_at = 2020-10-27T15:00:55.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.24.0" }
"0.24.1" = { created_at = 2020-10-28T16:46:48.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.24.1" }
"0.24.2" = { created_at = 2020-11-03T17:03:50.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.24.2" }
"0.24.3" = { created_at = 2020-11-09T11:43:50.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.24.3" }
"0.24.4" = { created_at = 2020-12-05T14:27:46.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.24.4" }
"0.25.0" = { created_at = 2021-01-02T19:10:59.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.25.0" }
"0.25.1" = { created_at = 2021-02-03T13:34:20.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.25.1" }
"0.26.0" = { created_at = 2021-03-13T06:17:10.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.26.0" }
"0.27.0" = { created_at = 2021-04-06T13:57:45.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.27.0" }
"0.27.1" = { created_at = 2021-05-22T04:25:16.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.27.1" }
"0.27.2" = { created_at = 2021-06-01T08:06:37.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.27.2" }
"0.27.3" = { created_at = 2021-10-15T15:07:44.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.27.3" }
"0.28.0" = { created_at = 2021-11-03T16:10:44.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.28.0" }
"0.29.0" = { created_at = 2021-12-24T16:56:56.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.29.0" }
"0.30.0" = { created_at = 2022-04-04T14:07:30.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.30.0" }
"0.31.0" = { created_at = 2022-07-21T14:07:12.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.31.0" }
"0.32.0" = { created_at = 2022-08-02T12:59:41.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.32.0" }
"0.32.1" = { created_at = 2022-08-08T15:01:15.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.32.1" }
"0.33.0" = { created_at = 2022-08-28T22:26:40.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.33.0" }
"0.34.0" = { created_at = 2022-09-28T14:30:15.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.34.0" }
"0.35.0" = { created_at = 2022-11-11T16:00:38.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.35.0" }
"0.35.1" = { created_at = 2022-11-18T11:45:18.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.35.1" }
"0.36.0" = { created_at = 2023-01-16T16:51:13.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.36.0" }
"0.37.0" = { created_at = 2023-01-24T13:18:39.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.37.0" }
"0.38.0" = { created_at = 2023-02-15T14:27:26.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.38.0" }
"0.39.0" = { created_at = 2023-04-02T14:37:51.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.39.0" }
"0.40.0" = { created_at = 2023-04-30T17:12:27.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.40.0" }
"0.41.0" = { created_at = 2023-05-25T15:32:09.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.41.0" }
"0.41.1" = { created_at = 2023-05-27T06:57:29.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.41.1" }
"0.42.0" = { created_at = 2023-06-14T15:42:35.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.42.0" }
"0.43.0" = { created_at = 2023-10-14T17:06:23.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.43.0" }
"0.44.0" = { created_at = 2023-11-12T13:10:54.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.44.0" }
"0.44.1" = { created_at = 2023-11-17T10:20:41.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.44.1" }
"0.45.0" = { created_at = 2024-01-01T06:41:32.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.45.0" }
"0.46.0" = { created_at = 2024-01-23T14:55:12.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.46.0" }
"0.46.1" = { created_at = 2024-02-01T09:15:52.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.46.1" }
"0.47.0" = { created_at = 2024-03-10T12:47:04.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.47.0" }
"0.48.0" = { created_at = 2024-03-13T15:14:40.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.48.0" }
"0.48.1" = { created_at = 2024-03-17T07:40:50.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.48.1" }
"0.49.0" = { created_at = 2024-04-04T15:23:06.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.49.0" }
"0.50.0" = { created_at = 2024-04-14T15:06:31.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.50.0" }
"0.51.0" = { created_at = 2024-05-01T05:37:01.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.51.0" }
"0.52.0" = { created_at = 2024-05-07T15:17:02.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.52.0" }
"0.52.1" = { created_at = 2024-05-13T16:56:16.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.52.1" }
"0.53.0" = { created_at = 2024-06-06T13:10:31.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/0.53.0" }
"0.54.0" = { created_at = 2024-07-08T13:54:24.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.54.0" }
"0.54.1" = { created_at = 2024-07-19T08:14:20.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.54.1" }
"0.54.2" = { created_at = 2024-07-26T10:12:30.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.54.2" }
"0.54.3" = { created_at = 2024-07-31T12:58:35.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.54.3" }
"0.55.0" = { created_at = 2024-08-29T08:13:56.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.55.0" }
"0.56.0" = { created_at = 2024-10-27T03:07:01.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.56.0" }
"0.56.1" = { created_at = 2024-11-10T14:25:02.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.56.1" }
"0.56.2" = { created_at = 2024-11-11T15:59:57.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.56.2" }
"0.56.3" = { created_at = 2024-11-15T01:07:53.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.56.3" }
"0.57.0" = { created_at = 2024-12-15T08:07:32.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.57.0" }
"0.58.0" = { created_at = 2025-01-19T17:11:30.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.58.0" }
"0.59.0" = { created_at = 2025-02-02T14:44:13.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.59.0" }
"0.60.0" = { created_at = 2025-02-12T16:02:18.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.60.0" }
"0.60.1" = { created_at = 2025-02-20T12:46:34.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.60.1" }
"0.60.2" = { created_at = 2025-02-23T11:25:47.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.60.2" }
"0.60.3" = { created_at = 2025-03-03T08:18:43.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.60.3" }
"0.61.0" = { created_at = 2025-03-30T10:57:42.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.61.0" }
"0.61.1" = { created_at = 2025-04-06T04:15:35.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.61.1" }
"0.61.2" = { created_at = 2025-04-20T02:42:25.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.61.2" }
"0.61.3" = { created_at = 2025-04-22T12:55:29.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.61.3" }
"0.62.0" = { created_at = 2025-05-04T10:00:03.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.62.0" }
"0.63.0" = { created_at = 2025-06-27T16:12:52.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.63.0" }
"0.64.0" = { created_at = 2025-07-06T15:05:40.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.64.0" }
"0.65.0" = { created_at = 2025-07-27T01:43:27.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.65.0" }
"0.65.1" = { created_at = 2025-08-03T05:51:14.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.65.1" }
"0.65.2" = { created_at = 2025-08-31T13:25:04.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.65.2" }
"0.66.0" = { created_at = 2025-10-12T13:24:17.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.66.0" }
"0.66.1" = { created_at = 2025-10-26T06:13:42.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.66.1" }
"0.67.0" = { created_at = 2025-11-16T11:04:23.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.67.0" }
"0.68.0" = { created_at = 2026-02-20T02:06:47.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.68.0" }
"0.70.0" = { created_at = 2026-03-02T08:02:17.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.70.0" }
"0.71.0" = { created_at = 2026-04-04T05:15:38.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.71.0" }
"0.72.0" = { created_at = 2026-04-26T09:09:58.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.72.0" }
"0.73.0" = { created_at = 2026-05-23T15:19:24.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.73.0" }
"0.73.1" = { created_at = 2026-05-25T05:37:25.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.73.1" }
"0.74.0" = { created_at = 2026-07-06T13:33:58.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.74.0" }
"0.74.1" = { created_at = 2026-07-18T12:54:00.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.74.1" }
"0.74.2" = { created_at = 2026-08-01T00:17:03.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.74.2" }
"0.74.3" = { created_at = 2026-08-17T03:10:34.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.74.3" }
"0.74.4" = { created_at = 2026-09-12T00:24:35.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.74.4" }
"0.74.5" = { created_at = 2026-10-11T02:39:32.000Z, release_url = "https://github.com/junegunn/fzf/releases/tag/v0.74.5" }
